module.exports = {
  song: [
    { id:  1, songName: '秒針を噛む' },
    { id:  2, songName: '脳裏上のクラッカー' },
    { id:  3, songName: 'ヒューマノイド' },
    { id:  4, songName: 'サターン' },
    { id:  5, songName: '雲丹と栗' },
    { id:  6, songName: '君がいて水になる' },
    { id:  7, songName: '眩しいDNAだけ' },
    { id:  8, songName: '正義' },
    { id:  9, songName: '勘冴えて悔しいわ' },
    { id: 10, songName: 'またね幻' },
    { id: 11, songName: 'マイノリティ脈絡' },
    { id: 12, songName: '彷徨い酔い温度' },
    { id: 13, songName: '蹴っ飛ばした毛布' },
    { id: 14, songName: 'こんなこと騒動' },
    { id: 15, songName: 'ハゼ馳せる果てるまで' },
    { id: 16, songName: 'Dear. Mr 「F」' },
    { id: 17, songName: '居眠り遠征隊' },
    { id: 18, songName: 'グラスとラムレーズン' },
    { id: 19, songName: '優しくLAST SMILE' },
    { id: 20, songName: 'お勉強しといてよ' },
    { id: 21, songName: 'MILABO' },
    { id: 22, songName: '低血ボルト' },
    { id: 23, songName: 'Ham' },
    { id: 24, songName: 'JK BOMBER' },
    { id: 25, songName: 'マリンブルーの庭園' },
    { id: 26, songName: '勘ぐれい' },
    { id: 27, songName: '正しくなれない' },
    { id: 28, songName: '暗く黒く' },
    { id: 29, songName: '胸の煙' },
    { id: 30, songName: 'はゔぁ' },
    { id: 31, songName: '機械油' },
    { id: 32, songName: 'ろんりねす' },
    { id: 33, songName: '繰り返す収穫' },
    { id: 34, songName: '過眠' },
    { id: 35, songName: '奥底に眠るルーツ' },
    { id: 36, songName: 'あいつら全員同窓会' },
    { id: 37, songName: 'ばかじゃないのに' },
    { id: 38, songName: '猫リセット' },
    { id: 39, songName: '違う曲にしようよ' },
    { id: 40, songName: '袖のキルト' },
    { id: 41, songName: '夜中のキスミ' },
    { id: 42, songName: 'ミラーチューン' },
    { id: 43, songName: '琥珀色の街、上海蟹の朝(くるりCover)' },
    { id: 45, songName: 'フルムーンダンシング(未公開曲)' },
  ]
};